-- Insert Development Buyers
BEGIN;

INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (1,'San Fillipo','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (2,'The Table','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (3,'Skillet','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (4,'Harvest Pizza - German Village','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (5,'Harvest Pizza - Clintonville','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (6,'Heirloom Café  (OSU)','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (7,'The Sycamore','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (9,'Basi Italia','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (10,'Explorers Club','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (11,'Westies Gastropub','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (12,'Alchemy Juice Bar and Café','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (13,'The Kitchen','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (14,'Yellow Bird','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (15,'Barcelona','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (16,'The Crest','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (17,'Black Creek Bistro','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (18,'Acre','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (19,'Native','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (20,'Wolf Ridge Brewery/Restaurant','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (21,'La Tavola','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (22,'Till','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (23,'G. Michaels','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (24,'Rigsbys','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (25,'Cameron Mitchell','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (26,'Rusty Bucket','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (27,'Strong Water','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (28,'Southside Roots Café','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (29,'Little Eater Produce and Provisions','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (30,'Staff','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (31,'LSS','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (33,'Compost','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (34,'North Market','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (35,'Clintonville Market','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (36,'Worthington Market','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (37,'400 West Rich Market','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (38,'Senior Distribution','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (39,'U-Pick','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (42,'Little Eater (Restaurant)','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (45,'CSA','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (46,'Southside Roots Market','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (47,'CSA - YP','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (48,'Primary One Cooking Demo','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (49,'MOF Farm Stand','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (50,'Double Comfort','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (51,'Carl Williamson','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (52,'Casey Slive','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (53,'Cooking Demo - Parsons Health Center','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (54,'Duncan''s Mom','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (55,'Ed (Cooking Demo)','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (56,'Farm Stand - Clarfield','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (57,'Farm Stand - Indoors Opportunity Center','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (58,'Farm Stand - Indoors Rec Center','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (59,'Farm Stand - Wheatland','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (60,'Fleeter','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (61,'Franklin Park Conservatory','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (62,'Franklinton Gardens','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (63,'Jeannice','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (64,'Kim''s mom','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (65,'Maggie','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (66,'Produce Basket Giveaway','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (67,'Sarah Lenkay','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (68,'Shalom Zone','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (69,'South Side HC (Sat AM pickup)','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (70,'Special Order','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (71,'Special Order - Clem Taylor','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (72,'Special Order - Martha Jones','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (73,'Special Order - Ms Williams','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (74,'Special Order - Robert Patterson','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (75,'Special Order - Vita King','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (76,'Special Order - Williams','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (77,'Sweet Carrot','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (78,'Youth Program Celebration','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (79,'Farm Stand','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (80,'Watkins Elementary School','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (81,'Terry Traster','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (82,'Special Order - Fleeter','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (83,'Special Order - Carl Williamson','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (84,'Robert Patterson','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (85,'Outreach Event','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (86,'OSU Community Garden Event','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (87,'Opportunity Center Grand Opening','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (88,'National Night Out','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (89,'Mary Beth','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (90,'Limited Brand Market','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (91,'Kawolski-Leonard Wedding','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (92,'Harvest','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (93,'Food Justice Project','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (94,'Farm Stand - Indoors','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (95,'Columbus Children''s Parade','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (96,'Charles Ingrott','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (97,'Amy','true','false');
INSERT INTO "buyer_information" (buyer_id,buyer_name, is_active, apply_large_order_discount) VALUES (98,'Fall Farm Celebration','true','false');

COMMIT;