-- Insert Production Items
BEGIN;

INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (1,'Acorn Squash','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (2,'Arugula','','Field','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (3,'Arugula','Baby','wait until dry','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (4,'Asparagus','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (5,'Baby Swiss Chard','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (6,'Basil','Green','HT2','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (7,'Basil','Purple','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (8,'Arugula','Baby ','Mid-size leaves','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (9,'Beets','Baby','Multicolored','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (10,'Beets','Baby - Golden','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (11,'Beets','Baby - Red','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (12,'Beets','Chioggia','Largest','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (13,'Beets','Golden','Largest','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (14,'Beets','Red','Largest','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (15,'Black beans','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (16,'Arugula','HT','Largest leaves','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (17,'Broccoli','','All Available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (18,'Butternut Squash','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (19,'Beets - BULK','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (20,'Cabbage','Green','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (21,'Cabbage','Red','All Available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (22,'Beets','','Clear out field bed, then harvest from HT if needed','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (23,'Carrots','Baby','Multicolored','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (24,'Beets','HT','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (25,'Cauliflower','','All Available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (26,'Chard','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (27,'Cheese Pumpkins','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (28,'Cabbage','','any varieties','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (29,'Cucumbers','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (30,'Delicata Squash','','All Available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (31,'Dill','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (32,'Braising Mix','','Mix of large chard, collards, green kale, mustard','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (33,'Carrots','Multicolored','Harvest from field','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (34,'Eggplant','Green Thai','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (35,'Eggplant','Japanese','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (36,'Eggplant','','Any variety','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (37,'Fennel','baby','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (38,'Flowers','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (39,'Garlic','','in shipping container','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (40,'Garlic','B Grade','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (41,'Carrots','Multicolored - BULK','Harvest all from field','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (42,'Green Beans','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (43,'Herb Starts','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (44,'Kale','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (45,'Carrots','','HT','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (46,'Collards','HT','1 leaf/plant','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (47,'Eggplant','Fairy Tale','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (48,'Fennel','','in shipping container','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (49,'Leeks','','Harvest 35 leeks','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (50,'Leeks','baby','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (51,'Garlic Scapes','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (52,'Lettuce','Baby Green','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (53,'Lettuce','Baby Red','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (54,'Kale','Baby','Red Russian only','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (55,'Lettuce','Full Size Green','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (56,'Lettuce','Full Size Red','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (57,'Mizuna','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (58,'Carrots','HT','Selectively harvest largest HT3','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (59,'Okra','','All Available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (60,'Okra','Green','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (61,'Okra','Red','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (62,'Onion','Red','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (63,'Onion','Spring','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (64,'Onion','White','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (65,'Onions','','All Available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (66,'Pac Choi','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (67,'Kale','Red Russian','Baby size - From field','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (68,'Patty Pan Squash','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (69,'Kale','Green ','1 leaf/plant','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (70,'Peppers','Bell','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (71,'Peppers','Green','Already harvested','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (72,'Peppers','Habaneros','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (73,'Kale','Lacinato','Field - clear out any available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (74,'Peppers','Hungarian Hot Wax','Wheatland - all available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (75,'Lettuce','','16 large heads','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (76,'Peppers','Jalapenos','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (77,'Peppers','Mini Sweet','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (78,'Lettuce','Baby','30 heads','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (79,'Peppers','Shishito','All Available - clear out beds','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (80,'Peppers','Padron','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (81,'Peppers','Hot','Already harvested','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (82,'Potatoes','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (83,'Potatoes','Fingerling','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (84,'Pumpkin','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (85,'Collards','','Field','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (86,'Radish - BULK','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (87,'Peppers','Thai Chile','Already harvested','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (88,'Radish','Easter Egg - Bulk','All Available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (89,'Radish','French Breakfast','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (90,'Parsley','','Clear cut plants','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (91,'Peppers','Sweet','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (92,'Scallions','Purple','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (93,'Radish','Easter Egg','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (94,'Spinach','Baby','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (95,'Spring Garlic','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (96,'Strawberries','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (97,'Summer Squash','','Pick all available- last harvest','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (98,'Peas','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (99,'Radish ','Purple Daikon','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (100,'Swiss Chard','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (101,'Peppers','Italian Sweet','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (102,'Radish','','Mix of Easter Egg (HT) and Watermelon (field)','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (103,'Kale','Baby ','3 lbs of RR baby kale kept separate; 10 lbs of RR/Green kale','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (104,'Tomatoes','','In shipping container','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (105,'Tomatoes','B Grade','Paste tomatoes','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (106,'Tomatoes','Cherry','In Shipping Container','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (107,'Tomatoes','Green','in shipping container','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (108,'Tomatoes','Heirloom','In Shipping Container','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (109,'Tomatoes','Paste','Ripe/slightly underripe','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (110,'Tomatoes','Slicer','All ripe, slightly underripe','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (111,'Turnip Greens','','harvest only greens from older beds','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (113,'Radish','Purple Daikon - BULK','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (114,'Turnips','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (115,'Watermelon','','In shipping container','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (116,'Mustard','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (117,'Zucchini','','Pick all available','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (118,'Radish','Easter Egg ','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (119,'Sage','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (120,'Radish','Watermelon','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (121,'Radish','HT','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (122,'Salad','Baby Mix','Harvest from field - two beds of lettuce','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (123,'Sunchoke','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (124,'Sweet Potato','','Pull all good ones','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (125,'Swiss Chard','Rainbow','From field','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (126,'Salad Mix','HT','Mix of medium size HT leaf lettuce, chard, kale, mustard, tat soi','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (127,'Turnips','Hakurei - BULK','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (128,'Thyme','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (129,'Turnips','Hakurei','Nicest greens - field turnips','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (130,'Scallions','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (131,'Spinach','','','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (132,'Swiss Chard','HT','1-2 leaves first from HT','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (133,'Turnips','Hakurei','Largest only (golf ball size)','true'); 
INSERT INTO item (item_id, item_type, item_variety, item_description, is_active) VALUES (134,'Winter Squash','','','true');

COMMIT;