-- Insert Development Buyers
BEGIN;

INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (101,'Finale','7842 Vel, Rd.','fermentum metus.','Detroit','MI','20221','Nam interdum enim non nisi. Aenean eget metus. In','(997) 637-3374','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','true','Lorem ipsum dolor sit', 'true', '0.2');
INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (102,'Lavasoft','Ap #857-6443 Sit Street','tristique aliquet.','Rockford','IL','96953','sit amet, faucibus ut, nulla. Cras','(805) 278-4309','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non,','true','Lorem ipsum dolor', 'false', '.1');
INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (103,'Google','Ap #265-4324 Pulvinar Ave','consectetuer euismod','Aurora','CO','48745','non lorem vitae odio sagittis semper. Nam tempor diam dictum','(483) 303-3362','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et','true','Lorem ipsum dolor sit amet', 'false', '.1');
INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (104,'Google','342-8167 Nulla Street','mauris erat','Hattiesburg','MS','72365','felis.','(623) 504-7742','Lorem','true','Lorem ipsum', 'false', '.1');
INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (105,'Chami','392-4440 Tellus Rd.','neque sed','Fort Smith','AR','71196','urna. Nunc quis arcu','(229) 857-1815','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','true','Lorem ipsum dolor', 'false', '.1');
INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (106,'Cakewalk','479-5059 Dolor Road','justo eu','Hartford','CT','90844','convallis est, vitae sodales nisi','(451) 411-5583','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.','true','Lorem', 'false', '.1');
INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (107,'Apple Systems','802-4731 Mauris Av.','ullamcorper eu,','Little Rock','AR','71852','ante bibendum ullamcorper. Duis','(428) 388-6185','Lorem ipsum dolor','true','Lorem ipsum', 'false', '.1');
INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (108,'Chami','P.O. Box 772, 2051 Nec Ave','sodales. Mauris','Fresno','CA','90647','Nam nulla magna, malesuada vel, convallis in, cursus et, eros.','(550) 631-9892','Lorem ipsum dolor sit amet, consectetuer','true','Lorem ipsum dolor', 'false', '.1');
INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (109,'Lycos','1765 Egestas Rd.','eu erat','Augusta','ME','60042','nulla vulputate dui, nec tempus','(286) 101-4113','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non,','true','Lorem ipsum dolor sit amet,', 'false', '.1');
INSERT INTO "buyer_information" (buyer_id,buyer_name,address1,address2,city,state_code,zipcode,delivery_times,contact_phone,notes,is_active,description, apply_large_order_discount, discount) VALUES (110,'Google','P.O. Box 482, 8641 Sagittis Avenue','eleifend vitae,','Little Rock','AR','71153','erat. Vivamus nisi.','(212) 584-5167','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing','true','Lorem ipsum dolor sit amet,', 'false', '.1');

COMMIT;